// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type AboutDocumentDataSlicesSlice = CardSlice;

/**
 * Content for About documents
 */
interface AboutDocumentData {
    /**
     * Slice Zone field in *About*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: about.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#slices
     */
    slices: prismic.SliceZone<AboutDocumentDataSlicesSlice> /**
     * Meta Description field in *About*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A brief summary of the page
     * - **API ID Path**: about.meta_description
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */;
    meta_description: prismic.KeyTextField;

    /**
     * Meta Image field in *About*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: about.meta_image
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    meta_image: prismic.ImageField<never>;

    /**
     * Meta Title field in *About*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A title of the page used for social media and search engines
     * - **API ID Path**: about.meta_title
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    meta_title: prismic.KeyTextField;
}

/**
 * About document from Prismic
 *
 * - **API ID**: `about`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutDocument<Lang extends string = string> =
    prismic.PrismicDocumentWithoutUID<
        Simplify<AboutDocumentData>,
        "about",
        Lang
    >;

type FooterDocumentDataSlicesSlice = NavigationSlice;

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
    /**
     * cc_text field in *Footer*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Made With ♥️
     * - **API ID Path**: footer.cc_text
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    cc_text: prismic.KeyTextField;

    /**
     * Slice Zone field in *Footer*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#slices
     */
    slices: prismic.SliceZone<FooterDocumentDataSlicesSlice>;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
    prismic.PrismicDocumentWithoutUID<
        Simplify<FooterDocumentData>,
        "footer",
        Lang
    >;

type HeaderDocumentDataSlicesSlice = NavigationSlice;

/**
 * Content for Header documents
 */
interface HeaderDocumentData {
    /**
     * name field in *Header*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Your Name Here
     * - **API ID Path**: header.name
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    name: prismic.KeyTextField;

    /**
     * Slice Zone field in *Header*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: header.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#slices
     */
    slices: prismic.SliceZone<HeaderDocumentDataSlicesSlice>;
}

/**
 * Header document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> =
    prismic.PrismicDocumentWithoutUID<
        Simplify<HeaderDocumentData>,
        "header",
        Lang
    >;

type HomeDocumentDataSlicesSlice = never;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
    /**
     * Slice Zone field in *Home*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: home.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#slices
     */
    slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
     * Meta Description field in *Home*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A brief summary of the page
     * - **API ID Path**: home.meta_description
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */;
    meta_description: prismic.KeyTextField;

    /**
     * Meta Image field in *Home*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: home.meta_image
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    meta_image: prismic.ImageField<never>;

    /**
     * Meta Title field in *Home*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A title of the page used for social media and search engines
     * - **API ID Path**: home.meta_title
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    meta_title: prismic.KeyTextField;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
    prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

type ProjectDocumentDataSlicesSlice = GallerySlice | TwoSplitSlice | HeroSlice;

/**
 * Content for Project documents
 */
interface ProjectDocumentData {
    /**
     * Slice Zone field in *Project*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: project.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#slices
     */
    slices: prismic.SliceZone<ProjectDocumentDataSlicesSlice> /**
     * Meta Description field in *Project*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A brief summary of the page
     * - **API ID Path**: project.meta_description
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */;
    meta_description: prismic.KeyTextField;

    /**
     * Meta Image field in *Project*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: project.meta_image
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    meta_image: prismic.ImageField<never>;

    /**
     * Meta Title field in *Project*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A title of the page used for social media and search engines
     * - **API ID Path**: project.meta_title
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    meta_title: prismic.KeyTextField;
}

/**
 * Project document from Prismic
 *
 * - **API ID**: `project`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectDocument<Lang extends string = string> =
    prismic.PrismicDocumentWithUID<
        Simplify<ProjectDocumentData>,
        "project",
        Lang
    >;

type ProjectsDocumentDataSlicesSlice = CardSlice;

/**
 * Content for Projects documents
 */
interface ProjectsDocumentData {
    /**
     * Slice Zone field in *Projects*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: projects.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#slices
     */
    slices: prismic.SliceZone<ProjectsDocumentDataSlicesSlice> /**
     * Meta Description field in *Projects*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A brief summary of the page
     * - **API ID Path**: projects.meta_description
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */;
    meta_description: prismic.KeyTextField;

    /**
     * Meta Image field in *Projects*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: projects.meta_image
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    meta_image: prismic.ImageField<never>;

    /**
     * Meta Title field in *Projects*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A title of the page used for social media and search engines
     * - **API ID Path**: projects.meta_title
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    meta_title: prismic.KeyTextField;
}

/**
 * Projects document from Prismic
 *
 * - **API ID**: `projects`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectsDocument<Lang extends string = string> =
    prismic.PrismicDocumentWithoutUID<
        Simplify<ProjectsDocumentData>,
        "projects",
        Lang
    >;

export type AllDocumentTypes =
    | AboutDocument
    | FooterDocument
    | HeaderDocument
    | HomeDocument
    | ProjectDocument
    | ProjectsDocument;

/**
 * Primary content in *Cards → Primary*
 */
export interface CardSliceDefaultPrimary {
    /**
     * title field in *Cards → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: card.primary.title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField;

    /**
     * subtitle field in *Cards → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: card.primary.subtitle
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    subtitle: prismic.KeyTextField;

    /**
     * background_image field in *Cards → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: card.primary.background_image
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    background_image: prismic.ImageField<never>;

    /**
     * action_link field in *Cards → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: #
     * - **API ID Path**: card.primary.action_link
     * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
     */
    action_link: prismic.LinkField;

    /**
     * text_position field in *Cards → Primary*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: left
     * - **API ID Path**: card.primary.text_position
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    text_position: prismic.SelectField<
        "left" | "right" | "top" | "bottom",
        "filled"
    >;

    /**
     * background_color field in *Cards → Primary*
     *
     * - **Field Type**: Color
     * - **Placeholder**: *None*
     * - **API ID Path**: card.primary.background_color
     * - **Documentation**: https://prismic.io/docs/field#color
     */
    background_color: prismic.ColorField;

    /**
     * card_width field in *Cards → Primary*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: 1
     * - **API ID Path**: card.primary.card_width
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    card_width: prismic.SelectField<"1" | "2", "filled">;

    /**
     * image_dark field in *Cards → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: card.primary.image_dark
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    image_dark: prismic.ImageField<never>;

    /**
     * image_light field in *Cards → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: card.primary.image_light
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    image_light: prismic.ImageField<never>;
}

/**
 * Primary content in *Cards → Items*
 */
export interface CardSliceDefaultItem {
    /**
     * image field in *Cards → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: card.items[].image
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    image: prismic.ImageField<never>;
}

/**
 * simple variation for Cards Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardSliceDefault = prismic.SharedSliceVariation<
    "default",
    Simplify<CardSliceDefaultPrimary>,
    Simplify<CardSliceDefaultItem>
>;

/**
 * Primary content in *Cards → Primary*
 */
export interface CardSliceSlidePrimary {
    /**
     * title field in *Cards → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: card.primary.title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField;
}

/**
 * Primary content in *Cards → Items*
 */
export interface CardSliceSlideItem {
    /**
     * image field in *Cards → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: card.items[].image
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    image: prismic.ImageField<never>;
}

/**
 * slide variation for Cards Slice
 *
 * - **API ID**: `slide`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardSliceSlide = prismic.SharedSliceVariation<
    "slide",
    Simplify<CardSliceSlidePrimary>,
    Simplify<CardSliceSlideItem>
>;

/**
 * Primary content in *Cards → Primary*
 */
export interface CardSliceLinkCardPrimary {
    /**
     * title field in *Cards → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: card.primary.title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField;

    /**
     * background_color field in *Cards → Primary*
     *
     * - **Field Type**: Color
     * - **Placeholder**: *None*
     * - **API ID Path**: card.primary.background_color
     * - **Documentation**: https://prismic.io/docs/field#color
     */
    background_color: prismic.ColorField;

    /**
     * action_link field in *Cards → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: #
     * - **API ID Path**: card.primary.action_link
     * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
     */
    action_link: prismic.LinkField;

    /**
     * button_pos field in *Cards → Primary*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: top-right
     * - **API ID Path**: card.primary.button_pos
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    button_pos: prismic.SelectField<
        "top-right" | "top-left" | "bot-left" | "bot-right",
        "filled"
    >;

    /**
     * card_width field in *Cards → Primary*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: 1
     * - **API ID Path**: card.primary.card_width
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    card_width: prismic.SelectField<"1" | "2", "filled">;

    /**
     * bg_image_dark field in *Cards → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: card.primary.bg_image_dark
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    bg_image_dark: prismic.ImageField<never>;

    /**
     * bg_image_light field in *Cards → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: card.primary.bg_image_light
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    bg_image_light: prismic.ImageField<never>;
}

/**
 * Link Card variation for Cards Slice
 *
 * - **API ID**: `linkCard`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardSliceLinkCard = prismic.SharedSliceVariation<
    "linkCard",
    Simplify<CardSliceLinkCardPrimary>,
    never
>;

/**
 * Primary content in *Cards → Primary*
 */
export interface CardSliceCardWithVideoPrimary {
    /**
     * title field in *Cards → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: card.primary.title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField;

    /**
     * subtitle field in *Cards → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: card.primary.subtitle
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    subtitle: prismic.KeyTextField;

    /**
     * background_image field in *Cards → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: card.primary.background_image
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    background_image: prismic.ImageField<never>;

    /**
     * action_link field in *Cards → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: #
     * - **API ID Path**: card.primary.action_link
     * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
     */
    action_link: prismic.LinkField;

    /**
     * text_position field in *Cards → Primary*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: left
     * - **API ID Path**: card.primary.text_position
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    text_position: prismic.SelectField<
        "left" | "right" | "top" | "bottom",
        "filled"
    >;

    /**
     * background_color field in *Cards → Primary*
     *
     * - **Field Type**: Color
     * - **Placeholder**: *None*
     * - **API ID Path**: card.primary.background_color
     * - **Documentation**: https://prismic.io/docs/field#color
     */
    background_color: prismic.ColorField;

    /**
     * card_width field in *Cards → Primary*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: 1
     * - **API ID Path**: card.primary.card_width
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    card_width: prismic.SelectField<"1" | "2", "filled">;
}

/**
 * Primary content in *Cards → Items*
 */
export interface CardSliceCardWithVideoItem {
    /**
     * image field in *Cards → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: card.items[].image
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    image: prismic.ImageField<never>;
}

/**
 * Card With Video variation for Cards Slice
 *
 * - **API ID**: `cardWithVideo`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardSliceCardWithVideo = prismic.SharedSliceVariation<
    "cardWithVideo",
    Simplify<CardSliceCardWithVideoPrimary>,
    Simplify<CardSliceCardWithVideoItem>
>;

/**
 * Primary content in *Cards → Primary*
 */
export interface CardSliceTitleCardPrimary {
    /**
     * title field in *Cards → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: card.primary.title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField;

    /**
     * background_color field in *Cards → Primary*
     *
     * - **Field Type**: Color
     * - **Placeholder**: *None*
     * - **API ID Path**: card.primary.background_color
     * - **Documentation**: https://prismic.io/docs/field#color
     */
    background_color: prismic.ColorField;

    /**
     * action_link field in *Cards → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: #
     * - **API ID Path**: card.primary.action_link
     * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
     */
    action_link: prismic.LinkField;

    /**
     * button_pos field in *Cards → Primary*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: 2
     * - **API ID Path**: card.primary.button_pos
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    button_pos: prismic.SelectField<"2" | "1" | "3" | "4", "filled">;

    /**
     * card_width field in *Cards → Primary*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: 1
     * - **API ID Path**: card.primary.card_width
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    card_width: prismic.SelectField<"1" | "2", "filled">;

    /**
     * bg_image_dark field in *Cards → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: card.primary.bg_image_dark
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    bg_image_dark: prismic.ImageField<never>;

    /**
     * bg_image_light field in *Cards → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: card.primary.bg_image_light
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    bg_image_light: prismic.ImageField<never>;
}

/**
 * titleCard variation for Cards Slice
 *
 * - **API ID**: `titleCard`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardSliceTitleCard = prismic.SharedSliceVariation<
    "titleCard",
    Simplify<CardSliceTitleCardPrimary>,
    never
>;

/**
 * Primary content in *Cards → Primary*
 */
export interface CardSliceFullBackgroundCardPrimary {
    /**
     * title field in *Cards → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: card.primary.title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField;

    /**
     * action_link field in *Cards → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: #
     * - **API ID Path**: card.primary.action_link
     * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
     */
    action_link: prismic.LinkField;

    /**
     * card_width field in *Cards → Primary*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: 1
     * - **API ID Path**: card.primary.card_width
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    card_width: prismic.SelectField<"1" | "2", "filled">;

    /**
     * bg_image_dark field in *Cards → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: card.primary.bg_image_dark
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    bg_image_dark: prismic.ImageField<never>;

    /**
     * bg_image_light field in *Cards → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: card.primary.bg_image_light
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    bg_image_light: prismic.ImageField<never>;

    /**
     * button_pos field in *Cards → Primary*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: bot-right
     * - **API ID Path**: card.primary.button_pos
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    button_pos: prismic.SelectField<
        "bot-right" | "bot-left" | "top-left" | "top-right",
        "filled"
    >;
}

/**
 * Full Background Card variation for Cards Slice
 *
 * - **API ID**: `fullBackgroundCard`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardSliceFullBackgroundCard = prismic.SharedSliceVariation<
    "fullBackgroundCard",
    Simplify<CardSliceFullBackgroundCardPrimary>,
    never
>;

/**
 * Primary content in *Cards → Primary*
 */
export interface CardSliceSpotifyPrimary {
    /**
     * button_pos field in *Cards → Primary*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: top-right
     * - **API ID Path**: card.primary.button_pos
     * - **Documentation**: https://prismic.io/docs/field#select
     */
    button_pos: prismic.SelectField<
        "top-right" | "top-left" | "bot-left" | "bot-right",
        "filled"
    >;
}

/**
 * spotify variation for Cards Slice
 *
 * - **API ID**: `spotify`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardSliceSpotify = prismic.SharedSliceVariation<
    "spotify",
    Simplify<CardSliceSpotifyPrimary>,
    never
>;

/**
 * Slice variation for *Cards*
 */
type CardSliceVariation =
    | CardSliceDefault
    | CardSliceSlide
    | CardSliceLinkCard
    | CardSliceCardWithVideo
    | CardSliceTitleCard
    | CardSliceFullBackgroundCard
    | CardSliceSpotify;

/**
 * Cards Shared Slice
 *
 * - **API ID**: `card`
 * - **Description**: Card
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardSlice = prismic.SharedSlice<"card", CardSliceVariation>;

/**
 * Primary content in *Gallery → Items*
 */
export interface GallerySliceDefaultItem {
    /**
     * gallery_image field in *Gallery → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: gallery.items[].gallery_image
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    gallery_image: prismic.ImageField<never>;
}

/**
 * Default variation for Gallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GallerySliceDefault = prismic.SharedSliceVariation<
    "default",
    Record<string, never>,
    Simplify<GallerySliceDefaultItem>
>;

/**
 * Slice variation for *Gallery*
 */
type GallerySliceVariation = GallerySliceDefault;

/**
 * Gallery Shared Slice
 *
 * - **API ID**: `gallery`
 * - **Description**: Gallery
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GallerySlice = prismic.SharedSlice<
    "gallery",
    GallerySliceVariation
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceDefaultPrimary {
    /**
     * hero_image field in *Hero → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: hero.primary.hero_image
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    hero_image: prismic.ImageField<never>;
}

/**
 * Full Background variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
    "default",
    Simplify<HeroSliceDefaultPrimary>,
    never
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceHeroWithHeaderPrimary {
    /**
     * hero_image field in *Hero → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: hero.primary.hero_image
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    hero_image: prismic.ImageField<never>;

    /**
     * hero_link field in *Hero → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: hero.primary.hero_link
     * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
     */
    hero_link: prismic.LinkField;

    /**
     * hero_header field in *Hero → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: hero.primary.hero_header
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    hero_header: prismic.KeyTextField;

    /**
     * hero_subheader field in *Hero → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: hero.primary.hero_subheader
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    hero_subheader: prismic.KeyTextField;
}

/**
 * Hero with header variation for Hero Slice
 *
 * - **API ID**: `heroWithHeader`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceHeroWithHeader = prismic.SharedSliceVariation<
    "heroWithHeader",
    Simplify<HeroSliceHeroWithHeaderPrimary>,
    never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault | HeroSliceHeroWithHeader;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *Navigation → Items*
 */
export interface NavigationSliceDefaultItem {
    /**
     * link_text field in *Navigation → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.items[].link_text
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    link_text: prismic.KeyTextField;

    /**
     * link field in *Navigation → Items*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.items[].link
     * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
     */
    link: prismic.LinkField;
}

/**
 * Default variation for Navigation Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigationSliceDefault = prismic.SharedSliceVariation<
    "default",
    Record<string, never>,
    Simplify<NavigationSliceDefaultItem>
>;

/**
 * Slice variation for *Navigation*
 */
type NavigationSliceVariation = NavigationSliceDefault;

/**
 * Navigation Shared Slice
 *
 * - **API ID**: `navigation`
 * - **Description**: Navigation
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigationSlice = prismic.SharedSlice<
    "navigation",
    NavigationSliceVariation
>;

/**
 * Primary content in *TwoSplit → Primary*
 */
export interface TwoSplitSliceDefaultPrimary {
    /**
     * primary_image field in *TwoSplit → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: two_split.primary.primary_image
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    primary_image: prismic.ImageField<never>;

    /**
     * heading field in *TwoSplit → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: two_split.primary.heading
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    heading: prismic.KeyTextField;

    /**
     * secondary_heading field in *TwoSplit → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: two_split.primary.secondary_heading
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    secondary_heading: prismic.KeyTextField;

    /**
     * paragraph field in *TwoSplit → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: two_split.primary.paragraph
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    paragraph: prismic.KeyTextField;
}

/**
 * Default variation for TwoSplit Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TwoSplitSliceDefault = prismic.SharedSliceVariation<
    "default",
    Simplify<TwoSplitSliceDefaultPrimary>,
    never
>;

/**
 * Primary content in *TwoSplit → Primary*
 */
export interface TwoSplitSliceTwoImagePrimary {
    /**
     * primary_image field in *TwoSplit → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: two_split.primary.primary_image
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    primary_image: prismic.ImageField<never>;

    /**
     * secondary_image field in *TwoSplit → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: two_split.primary.secondary_image
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    secondary_image: prismic.ImageField<never>;

    /**
     * heading field in *TwoSplit → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: two_split.primary.heading
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    heading: prismic.KeyTextField;

    /**
     * secondary_heading field in *TwoSplit → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: two_split.primary.secondary_heading
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    secondary_heading: prismic.KeyTextField;

    /**
     * paragraph field in *TwoSplit → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: two_split.primary.paragraph
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    paragraph: prismic.KeyTextField;
}

/**
 * TwoImage variation for TwoSplit Slice
 *
 * - **API ID**: `twoImage`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TwoSplitSliceTwoImage = prismic.SharedSliceVariation<
    "twoImage",
    Simplify<TwoSplitSliceTwoImagePrimary>,
    never
>;

/**
 * Slice variation for *TwoSplit*
 */
type TwoSplitSliceVariation = TwoSplitSliceDefault | TwoSplitSliceTwoImage;

/**
 * TwoSplit Shared Slice
 *
 * - **API ID**: `two_split`
 * - **Description**: TwoSplit
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TwoSplitSlice = prismic.SharedSlice<
    "two_split",
    TwoSplitSliceVariation
>;

declare module "@prismicio/client" {
    interface CreateClient {
        (
            repositoryNameOrEndpoint: string,
            options?: prismic.ClientConfig,
        ): prismic.Client<AllDocumentTypes>;
    }

    namespace Content {
        export type {
            AboutDocument,
            AboutDocumentData,
            AboutDocumentDataSlicesSlice,
            FooterDocument,
            FooterDocumentData,
            FooterDocumentDataSlicesSlice,
            HeaderDocument,
            HeaderDocumentData,
            HeaderDocumentDataSlicesSlice,
            HomeDocument,
            HomeDocumentData,
            HomeDocumentDataSlicesSlice,
            ProjectDocument,
            ProjectDocumentData,
            ProjectDocumentDataSlicesSlice,
            ProjectsDocument,
            ProjectsDocumentData,
            ProjectsDocumentDataSlicesSlice,
            AllDocumentTypes,
            CardSlice,
            CardSliceDefaultPrimary,
            CardSliceDefaultItem,
            CardSliceSlidePrimary,
            CardSliceSlideItem,
            CardSliceLinkCardPrimary,
            CardSliceCardWithVideoPrimary,
            CardSliceCardWithVideoItem,
            CardSliceTitleCardPrimary,
            CardSliceFullBackgroundCardPrimary,
            CardSliceSpotifyPrimary,
            CardSliceVariation,
            CardSliceDefault,
            CardSliceSlide,
            CardSliceLinkCard,
            CardSliceCardWithVideo,
            CardSliceTitleCard,
            CardSliceFullBackgroundCard,
            CardSliceSpotify,
            GallerySlice,
            GallerySliceDefaultItem,
            GallerySliceVariation,
            GallerySliceDefault,
            HeroSlice,
            HeroSliceDefaultPrimary,
            HeroSliceHeroWithHeaderPrimary,
            HeroSliceVariation,
            HeroSliceDefault,
            HeroSliceHeroWithHeader,
            NavigationSlice,
            NavigationSliceDefaultItem,
            NavigationSliceVariation,
            NavigationSliceDefault,
            TwoSplitSlice,
            TwoSplitSliceDefaultPrimary,
            TwoSplitSliceTwoImagePrimary,
            TwoSplitSliceVariation,
            TwoSplitSliceDefault,
            TwoSplitSliceTwoImage,
        };
    }
}
