// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
    card: dynamic(() => import("./Cards")),
    navigation: dynamic(() => import("./Navigation")),
};
